### RELEVANT PATHS TO CREATE THE CONNECTOME ###
paths:  
  dataset_dir: "/home/joanfr/Documents/Data-Tumor"
  atlas_path: "/home/joanfr/Documents/Utils/AAL3/AAL3v1_1mm.nii.gz"
  
  # If null, then output is in the 'dataset_dir'
  output_dir: "/home/joanfr/Documents/Hybrid-Examples_Review-1st/" 

  session: "*preop*" # opts: "preop", "psotop" // "*" means all sessions available
  subject: "sub-PAT16" #"sub-PAT16"      # "*" means all subjects available. IMPORTANT: Use the "*" wildcard for regex
  skip_subjects: ""  # List of subjects to skip

### SPACE TO WHICH IS REGISTERED ###
space: "MNI" # opts: "MNI", "dwi", "anat" 

### fODF RECONSTRUCTION METHOD TO USE ###
recons: "hybrid" # opts: "MSMT-CSD", "SS3T-CSD", "hybrid"// if null: uses MSMT_CSD 
shell:  # Only used for single shell methods
  b_val: "2800"
  num: "4" # b=0 is shell number 1

### TRACTOGRAPHY OPTIONS ###
trac:
  method: ACT # [ACT, Null] # Not applied when hybrid
  cutoff: "0.08" # FOD amplitude threshold - Only used inside the patological volume of the 5TT image (5th volume)
  seeding: "dynamic" # "gwmwi" / "random" / "dynamic"
  streams: "100000"
  seed_num: "5000000"
  max_len: "280" # In voxelsize units   
  min_len: "3" # In voxelsize units
  save_trk: False
  keep_full_tck: True
  sift2_tikhonov: "0.1"
  sift2_tv: "0.08"

### Type of lesion ###
lesion: "tumor" # This corresponds to the name of the binary mask of the lesion

### DELETE INTERMEDIATE FILEs ###
delete: 
  response_funcs: False
  fODFs: False
  WM_fODF: False
  seeding_mask: False
  bias_corr: False
  seg_5tt: False
  single_shells: False # Only applies to Single Shell extraction methods
  lesion_1mm: False
  weights_sift2: False

### PROCESSING TYPE ###
process: "single" # [multi, single] processing of subjects

### NUMBER OF THREADS TO launch ###
threads: "1"

### SKIP EXISTING FILES ###
skip: True
